name: CI Pipeline for Native Delight Next.js Frontend
run-name: Build and Deploy Frontend by ${{ github.actor }} 🚀

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./admin  # Matches your app in 'admin' subfolder
    env:
      NODE_VERSION: '20'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify package-lock.json
        run: 'test -f package-lock.json || echo "Warning: package-lock.json not found, caching may not work"'
        shell: bash
        continue-on-error: true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript type check
        run: npm run type-check || echo "No type-check script, skipping (Next.js build will check types)"
        continue-on-error: true

      - name: Build Next.js
        run: npm run build

      - name: Run tests
        run: 'npm test || echo "No tests defined, skipping"'
        shell: bash
        continue-on-error: true

      - name: List built files
        run: 'ls -la .next || echo "Build directory not found, check next.config.js"'
        shell: bash
        continue-on-error: true

      - name: Job status
        run: 'echo "✅ Job status: ${{ job.status }}"'
        shell: bash

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'  # Fixed to match 'master' branch
    steps:
      - name: Deploy to Contabo VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "Starting deployment..."
            cd ~/app/native_delight/admin || { echo "Failed to cd to ~/app/native_delight/admin"; exit 1; }
            echo "Current directory: $(pwd)"
            git fetch origin
            git checkout master
            git pull origin master || { echo "Git pull failed"; exit 1; }
            echo "Git pull completed. Current commit: $(git rev-parse HEAD)"
            npm ci || { echo "npm ci failed"; exit 1; }
            npm run build || { echo "npm run build failed"; exit 1; }
            echo "Build completed. Listing .next folder:"
            ls -la .next
            pm2 restart admin || { echo "PM2 restart failed"; exit 1; }
            echo "Deployment completed successfully"
            sudo systemctl restart nginx